Add ClassExpression to IsFunctionDefinition.
Summary:
Because I saw a ton of failing test262 tests on another one of my PRs, related to the ClassExpression change I made:
```
		Error: Unexpected AST form : ClassExpression
		    at IsFunctionDefinition (/home/ubuntu/prepack/lib/methods/is.js:295:13)
		    at IsAnonymousFunctionDefinition (/home/ubuntu/prepack/lib/methods/is.js:302:8)
		    at exports.default (/home/ubuntu/prepack/lib/evaluators/VariableDeclaration.js:44:13)
		    at LexicalEnvironment.evaluateAbstract (/home/ubuntu/prepack/lib/environment.js:1311:16)
		    at LexicalEnvironment.evaluate (/home/ubuntu/prepack/lib/environment.js:1298:22)
		    at exports.default (/home/ubuntu/prepack/lib/evaluators/Program.js:24:32)
		    at LexicalEnvironment.evaluateAbstract (/home/ubuntu/prepack/lib/environment.js:1311:16)
		    at LexicalEnvironment.evaluate (/home/ubuntu/prepack/lib/environment.js:1298:22)
		    at exports.default (/home/ubuntu/prepack/lib/evaluators/File.js:8:14)
		    at LexicalEnvironment.evaluateAbstract (/home/ubuntu/prepack/lib/environment.js:1311:16)
		    at LexicalEnvironment.evaluate (/home/ubuntu/prepack/lib/environment.js:1298:22)
```
Closes https://github.com/facebook/prepack/pull/769

Differential Revision: D5345348

Pulled By: hermanventer

fbshipit-source-id: ea0ec8ae9e8ca9869aaa096dbf75b3791180a676